### ISSUE TITLE
It's easy to forget to click "Update" and lose work

### ISSUE THREAD

**Issue by idbrii** [mhgolkar/Arrow#1]
I started making a simple story and it took me a bit to figure out why my work was disappearing each time I created a new node. I even tried Ctrl-s, but it was still gone.

Turns out I didn't see the Update button.

Would be nice to auto update or something to require fewer clicks.

**Comment by mhgolkar** [comment]
You're right.

I'll add *Auto-update* functionality and a toggle button for it (similar to `Auto-inspect`,)
together with possibly some kind of node-specific revision history in upcoming  releases.

> Quick Note: you can also use `Ctrl + Shift + Plus sign` shortcut to update a node.

**Comment by mhgolkar** [comment]
Now we have them in v1.1.0. 
*Auto-node-update* is now available and active by default. You can find it in *quick preferences*.

With auto-node-update on, if you deselect a node (click on the grid) or select another one, you'll get an auto update.
Selecting the same node resets the parameters.

To make sure users won't lose their data accidentally, inspector tracks last (7) changes,
and user can go back to them via back and fore buttons adjacent to the reset button.
