### ISSUE TITLE
Dialog character

### ISSUE THREAD

**Issue by premedios** [mhgolkar/Arrow#10]
In the screenshot, there are various dialogs with different characters. How do I create a new character other than "Anonymous"?

**Comment by mhgolkar** [comment]
Hi @premedios 

In the `Inspector` panel,  switch to the `Characters` tab.
If the tab is not visible use the arrow shaped buttons in the top-right corner of the panel to move tabs.
In the `Characters` tab click `new`, and in the form you'll see type a name for your character and choose a color.
Click `set` to keep the changes.
Now you can go back to any dialog node and choose this new character.

I'll update Arrow's wiki on this as soon as possible. You may check it out later.

Thanks for using Arrow
