### ISSUE TITLE
template/profile/localVariables for "character"

### ISSUE THREAD

**Issue by whwptb** [mhgolkar/Arrow#12]
(not an issue but a feature suggestion or a query if it might be possible to implement)

as of writing, "characters" made on the characters tab are only constant strings that has no other functions other than the dialog node

maybe there would be merit to having a dedicated space where the user could type in information about the "character"?

ie, 

Name:
sex:
age:
defining feature:
personality:
background story:

having those information are important on building a story.

there are also "statistics" values that could be added such as 

HP:
MP:
str:

etc

i know they could easily be added as the current implementation of variables, but having variables like those is in the long run, messy

ie

char1_hp
char2_hp

These information are also highly dependent on what story would be written, so maybe leaving them as just "custom" info would suffice

you could look at them as local variables inside the characters themselves instead of having them as global variables

(big thanks about the Variable parsing ^_^)

**Comment by mhgolkar** [comment]
Interesting!

**Comment by mhgolkar** [comment]
`v2.0.0` introduces a new [Character Tag System][characters], allowing to assign dynamically defined data to characters and expose them in textual nodes. They can as well be modified using `Tag-Edit` node and checked using `Tag-Pass`, in runtime.
I think they cover most of what you suggested.
For numeral statistics (HP, score, etc.) the solution might be to [still] use Variables, but tags offer many advantages for everything else with expected values or enumerated data.


[characters]: https://github.com/mhgolkar/Arrow/wiki/characters
