### ISSUE TITLE
sorting options on the items at the inspector

### ISSUE THREAD

**Issue by whwptb** [mhgolkar/Arrow#13]
as of writing, items at the inspector bar such as the variables, character or scenes and projects are just arranged from the first declared item to the last declared item

it would make it easier to use if a sort function for each category could be implemented

alphabetical sorting would hugely be beneficial.

projects and scenes could also be arranged by date(may it be created or modified)

**Comment by mhgolkar** [comment]
New `v2.0.0` allows filtering listed resources by name. Variables can be filtered by type too. We can also use list filtering to query in initialized tags (key and value) for listed Characters.
Alphabetical sorting is now available as well.
