### ISSUE TITLE
description of projects and scenes that could be viewed on the inspector bar

### ISSUE THREAD

**Issue by whwptb** [mhgolkar/Arrow#14]
hi

the end user would eventually make many projects and many many many scenes
(in my case "chapters", "scenes" and "sub-scenes")

it would be helpful and faster for the end user to have a place where they could add a description for the scenes(chapters), and to an extent to the projects

**Comment by mhgolkar** [comment]
Hi @whwptb 

This is implemented in `v1.5.0` using `entry` nodes' `notes` property.
Each scene, macro or project requires an `entry` node. The notes on each entry node will be shown as description of the parent scene/macro/project in the respective lists.
