### ISSUE TITLE
setting variable with random value

### ISSUE THREAD

**Issue by whwptb** [mhgolkar/Arrow#16]
adding an option on the [variable update node] to set the variable with a randomly generated value

- number variables could have an input range (start,end)

- string variables could have an input of pool of letters to which the string would be gotten and an input of range (how many letters to input)

**Comment by mhgolkar** [comment]
Hi @whwptb 

Now (v1.3.0+) we have a new built-in node type called `Generator` for the purpose you suggested.

This new node type can create and set value for its target variable, depending on the type and a set of user-defined rules.
The result can be:
+ Random positive or negative integer within a range and optionally filtering even or odd numbers.
+ Random ASCII string with a length and optionally using a pool of characters.
+ Randomly chosen string from a list of `|` separated strings. 
+ Random Boolean (`true` or `false`)
