### ISSUE TITLE
Node dropping isn't very forgiving

### ISSUE THREAD

**Issue by idbrii** [mhgolkar/Arrow#2]
This isn't close enough to connect nodes but there are no other nodes.

![image](https://user-images.githubusercontent.com/43559/110533669-17c25a80-80d3-11eb-8d56-a533de6cb775.png)

Makes it difficult to use for low dexterity people or to use quickly.

**Comment by mhgolkar** [comment]
There are a lot of small yet important details I shall take care of, including this and other UI improvements such as icons for nodes and buttons, pixel-perfecting the main theme, etc.
This will be a priority.

**Comment by mhgolkar** [comment]
Now (v1.4.0) we have new feature `Connection Assist`.
When user drags a connection to body of another node, Arrow will create a connection with the first available valid slot.
It's on by default and may be deactivated from quick preferences.

Thanks for your feedback @idbrii
