### ISSUE TITLE
A box like container box to place the nodes inside

### ISSUE THREAD

**Issue by whwptb** [mhgolkar/Arrow#20]
mainly for organizational purposes.
When there are many nodes already, it is helpful to place them on a box like container.

I am not familiar with other tools, but an example of this could be found on the nodes editor of unreal engine

**Comment by mhgolkar** [comment]
Does these containers have special functionalities? or act as pure visual organizers (a colorful background or frame wrapping nodes?)

**Comment by mhgolkar** [comment]
OK.  We now have `Frame` nodes. I hope they help.
