### ISSUE TITLE
canvas zooming out further 

### ISSUE THREAD

**Issue by whwptb** [mhgolkar/Arrow#21]
would help moving along the canvas.

The mini-map helps, but it is still different from moving along the main canvas itself, specially when you have many nodes and have to segment them to different spots of the canvas

**Comment by mhgolkar** [comment]
Prior to the Godot 3.4 the grid zoom functionality was quite limited specially regarding zoom.
Arrow uses the latest stable version, which now includes grid updates. I also revised the grid's default settings to allow from 10 to 400 percent zoom (0.1x to 4x.)
