### ISSUE TITLE
dragging along the mini-map

### ISSUE THREAD

**Issue by whwptb** [mhgolkar/Arrow#22]
as of writing, moving along the mini-map is limited to clicking.

It does work on surface level, but when seriously working on a project, clicking on the mini-map results to jumping and might get confusing, resulting on not using the mini-map altogether.

making the mini-map drag-to-move-along would help with this

**Comment by ArthyChaux** [comment]
I've created a pull request concerning that enhancement : #25

**Comment by mhgolkar** [comment]
Thanks

It's now done in `v1.5.0`.
You can also use the Godot's new native mini-map (activated by the respective button in top-left corner of the grid.)
Both mini-map solutions are by default available and are switchable.
