### ISSUE TITLE
location of newly created node

### ISSUE THREAD

**Issue by whwptb** [mhgolkar/Arrow#23]
when adding a new node, there are times that the node is not located on where the mouse cursor is.
Even if the mouse is clicked beforehand, it still does the said issue.

The node would also sometimes be buried under another node.

This causes confusion especially when the node comes off screen.

**Comment by mhgolkar** [comment]
Thanks @whwptb 

This is enhanced in `v1.5.0`.
The top-left corner of each newly placed node (inserted, pasted, dragged from slot, etc.) now lands on the most significant mouse position. It means where you release a dragged slot, or right-click to open the context-menu or the mouse position when pasting.
