### ISSUE TITLE
Arrow icons

### ISSUE THREAD

**Issue by ArthyChaux** [mhgolkar/Arrow#26]
It seems like the project is missing some icons, as it shows the Godot icon most of the time 
![image](https://user-images.githubusercontent.com/53626057/139958937-2729627c-766d-4285-8496-e7fcdc052a48.png)
![image](https://user-images.githubusercontent.com/53626057/139959015-ab1c39cc-c4f5-4fcd-b5ca-453d4cc220d0.png)

**Comment by mhgolkar** [comment]
Assets are fine!
That was me, forgetting to take care of a [workaround](https://docs.godotengine.org/en/3.4/tutorials/export/changing_application_icon_for_windows.html) required to changing executable icon for windows version.
