### ISSUE TITLE
Jump node clicking

### ISSUE THREAD

**Issue by ArthyChaux** [mhgolkar/Arrow#27]
I'm thinking about an enhancement that would be pretty useful for me. The idea is that when having a Jump node, you would be able to go where it's heading from the editor, to make keeping track of the scenes easier. I started trying with coding it, but I don't get the Mind system right now, but I was thinking about something looking like : 
![image](https://user-images.githubusercontent.com/53626057/139963582-c46ed302-4550-4868-83fa-7acbfe1009cf.png)
The button would be disabled when there is no destination set, and otherwise, when clicking on the button, it would focus the destination node, by changing scene if needed

**Comment by ArthyChaux** [comment]
Hoping that you'll like the idea, and hopefully implement it !

**Comment by mhgolkar** [comment]
I used `Double-click` to avoid adding a button and keeping the grid minimal as possible.
You can double-click on any `jump` or `macro_use` node to go-to/browse their targets.
