### ISSUE TITLE
Zooming In/Out with only WHEEL

### ISSUE THREAD

**Issue by ArthyChaux** [mhgolkar/Arrow#29]
Given that moving on the canvas is a really easy trick with WHEEL_BUTTON pressed, the shortcuts could be changed for more easy-to-use zooming.

I think that the use should be : 
 - WHEEL_SCROLL to zoom in and out
 - CTRL + WHEEL_SCROLL to move vertically
 - MAJ + WHEEL_SCROLL to move horizontally

Moreover, currently, CTRL + WHEEL_SCROLL  does not only zoom In/Out, but also scroll accordingly, which is even more annoying than the shortcuts.

Please tell me what you think about it, but as for me it would be game-changing for navigation use.
Thanks for considering it

**Comment by ArthyChaux** [comment]
The idea is that the GraphEdit has built-in inputs management which include : 

 - MOUSE_BUTTON dragging
 - node selection/linking/management (long to code manually)
 - MAJ + WHEEL_SCROLL to scroll horizontally
 - WHEEL_SCROLL to scroll vertically (in any other cases, including with CTRL, ALT pressed)

The issue with that is that it doesn't seem possible to override those inputs with GDScript, leading to the code you wrote in scripts/grid_graph_edit.gd, from line 522 to 538 being not well implemented.

Making the zoom on WHEEL_SCROLL and vertical/horizontal scroll with CTRL/MAJ as been added to 4.0, and is pretty easy to change : https://github.com/godotengine/godot/commit/bf5fa0c77f57bcb0cf908f6cffa319f3beea8fa6 (also define GraphEdit::set_zoom_custom too, but it's not big stuff it seems)

But I'm not sure that it'll be backported to 3.x though, so it would require forking the 3.x branch with that change. At least, from what I see, it should resolve all the issues said above.

If you don't want to bother forking the engine and compiling and all, I may be able to do it, just tell me if you're okay with it !

**Comment by ArthyChaux** [comment]
Okay, it seems like what i said is not true, as following https://github.com/godotengine/godot/blob/3.4-stable/CHANGELOG.md#gui-1, this change seems to be implemented in Godot 3.4.

**The final point is that you should consider migrating to Godot 3.4, as there should not be any incompatibilities**, but it would solve my issue and make my life easier

**Comment by mhgolkar** [comment]
Happily it's back-ported to Godot v3.4.x.
I removed the old workaround in favor of the native solution in `v1.5.0`.
