### ISSUE TITLE
Lots of clicks to make a new node

### ISSUE THREAD

**Issue by idbrii** [mhgolkar/Arrow#3]
To create a new node you must:

* right click
* double click node type
* drag pin to previous node
* select new node

If you could drag off a pin to open a node, you could simplify to:

* drag off pin and release
* double click node type

**Comment by mhgolkar** [comment]
Now (v1.3.0+) we have it.
You can drag and quick insert nodes from any of the incoming or outgoing slots.
> There is also a setting for even faster node creation :
> `QUICK_INSERT_NODES_ON_SINGLE_CLICK` (false in official releases)
