### ISSUE TITLE
Save window state in config.arrow

### ISSUE THREAD

**Issue by ArthyChaux** [mhgolkar/Arrow#31]
I think that saving the window preferences as fullscreen mode, maximised mode, should be saved in the config file so that on launch, the app restores as it was on last use.
I assume that it is not a complicated issue to solve, but could be a nice add !

**Comment by mhgolkar** [comment]
Thanks @ArthyChaux 

It's now implemented in v1.5.0.
Now Arrow stores the window state (position, size, full-screen, etc.) when you quit the app and restores it the next time you open it. Note that the exact behavior depends on the window-manager of the operating system.
