### ISSUE TITLE
Select a Chain of Nodes with MAJ/Shift

### ISSUE THREAD

**Issue by ArthyChaux** [mhgolkar/Arrow#33]
Currently, selecting multiple nodes can only be achieved by pressing CTRL, but I think it should also be possible with MAJ

**Comment by mhgolkar** [comment]
I believe the convention (or what we are mostly accustomed to) is that `Ctrl+Click` is used for multiple-selection and `Shift/MAJ+Click` is used for selecting all items between item A to item B (e.g. selecting a row of files in a file-manager.)
I think they shall not overlap.
But you made me think that we should be able to select all the nodes between two selected nodes (a chain;)
Therefore I change this issue to a feature-request for that.

**Comment by mhgolkar** [comment]
Now we have a branch selection with `Shift + Click` in `v2.x`.
> `Alt + Shift + Click` selects with sibling nodes.
