### ISSUE TITLE
Export to HTML seems broken

### ISSUE THREAD

**Issue by ArthyChaux** [mhgolkar/Arrow#34]
It seems like exporting to HTML shows the error message saying that Arrow does not have write access folder, even though exporting to JSON in that exact folder works just fine.
I can lead more tests if needed.

**Comment by mhgolkar** [comment]
Hi @ArthyChaux 

I can't reproduce the issue. Everything seems working well.
More tests will be fine, thanks. Please use the most recent version with debug mode (when exporting) and check the printed data in terminal.
Note also that for HTML export, Arrow needs two access:
1. Read access to the `./runtimes/html-js.arrow-runtime` to read the template
2. Write access to the export path

**Comment by ArthyChaux** [comment]
Okay, new tests worked fine, so nothing to worry about

**Comment by mhgolkar** [comment]
Thanks @ArthyChaux

**Comment by UlucKaymak** [comment]
I still get this error. I only tried to export JSON and HTML for this log file. 

[godot.log](https://github.com/user-attachments/files/22874895/godot.log)
