### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by andersmmg** [mhgolkar/Arrow#35]
Would be super nice if it remembered the size of the window when closed and restored it next time, also remembering if it's maximized or not

**Comment by mhgolkar** [comment]
Thanks @andersmmg 

It's now implemented in `v1.5.0`.
Now Arrow stores the window state (position, size, full-screen, etc.) when you quit the app and restores it the next time you open it. Note that the exact behavior depends on the window-manager of the operating system.
