### ISSUE TITLE
Quick Export key

### ISSUE THREAD

**Issue by tavurth** [mhgolkar/Arrow#36]
I'm using Arrow as the basis for dialog and interaction in my side scrolling VN.

Would be really useful to have a quick export button `Cmd + e` for example, as at the moment I have to use the following every time:
```
-> project 
-> export 
-> export json 
-> save 
-> confirm
``` 

It's a lot of steps.
Perhaps first time we can show the export screen but after that skip confirmation?

**Comment by mhgolkar** [comment]
Thanks for the suggestion @tavurth 

It's implemented in `v1.5.0`.
You can use `Ctrl+E` to re-export you project using the exact path and format of the most recent export (of current session.)
