### ISSUE TITLE
Ctrl + S not working (on Mac)

### ISSUE THREAD

**Issue by tavurth** [mhgolkar/Arrow#38]
When hovering the `save` button a tooltip `Ctrl + s` is shown, but this hotkey does not work on mac.

**Comment by mhgolkar** [comment]
Hi @tavurth 

I can't support Mac *properly* at the time (sorry for inconvenience;) 
But it might be a manifestation of some Godot v3.2 issues with cross-platform keybindings such as this one: 
https://github.com/godotengine/godot/pull/43662

The problem might be solved thanks to the new Godot updates (v3.4.x) which include a lot fixes and back-ported features from v4; Please update to new releases and check if it works.

P.S:
Just for the record. Currently, Mac users build their Arrow themselves. Configuring the [Input Map](https://docs.godotengine.org/en/stable/tutorials/inputs/input_examples.html#inputmap) if the problem remains, seems like an additional step to the process for the time being.
