### ISSUE TITLE
Render `{ Rich text with BBCode Content}`

### ISSUE THREAD

**Issue by zicklag** [mhgolkar/Arrow#39]
Hey there! I just discovered this and it seems pretty cool!

So far the biggest thing throwing me off is that when I run the game in the console, it displays all the content nodes without showing the content:

![image](https://user-images.githubusercontent.com/25393315/174667282-fcf838b4-1b67-493f-a8e6-506b59649048.png)

I know I can export the game to the browser, but to test it quickly it would be nice to be able to render that in the console.

I see that you have a brief that you can show in the console, but maybe it could be a checkmark in the settings to "show full content"?

**Comment by zicklag** [comment]
I just opened up the source and realized that the brief text has the same issue if you actually add content. It doesn't display it, it just renders it as `{ Rich text with BBCode Content }`. This looks like a simple bug. I'll see if I can figure it out.

**Comment by mhgolkar** [comment]
Hello @zicklag 

This was definitely a bug, now fixed. Thank you for pointing to it.
