### ISSUE TITLE
New feature: `Tag Match` node

### ISSUE THREAD

**Issue by MJacred** [mhgolkar/Arrow#44]
Currently, one would need a lot of `Tag Pass` nodes to branch like in a `switch` statement (Godot calls it `match`):

![image](https://user-images.githubusercontent.com/6639237/235369010-60db6f83-4e46-4337-8520-d4a1ea861d88.png)

That's why checking for multiple values would be highly beneficial.

Here's a mockup I thought up, which is basically a combination of `Tag Pass` + `Interaction` nodes:

![image](https://user-images.githubusercontent.com/6639237/235368719-441b6e77-6a1c-4f79-abdf-248ef763c892.png)

![image](https://user-images.githubusercontent.com/6639237/235368984-7ef9f30d-2b4e-4edd-8131-c312b1af9b18.png)

**Comment by mhgolkar** [comment]
Thanks @MJacred 
This is a pretty good idea. I think we should plan for implementing it.
There are a lot to be done before this though, so it may take some time. If you can implement it, a pull-request would be very welcome.

**Comment by mhgolkar** [comment]
We have it now in `v2.2.0`
