### ISSUE TITLE
Enhancement: Allow updating several Variables / Character-tag-values in one node

### ISSUE THREAD

**Issue by MJacred** [mhgolkar/Arrow#45]
Right now, if you want to update several variables in one go, you need to chain them like this. The same goes for Character-tag-values. Updating several at once in one node would save a lot of space in the graph.

![image](https://user-images.githubusercontent.com/6639237/235369244-7a109738-b61d-422b-89bc-4fa1977f36a9.png)

**Comment by mhgolkar** [comment]
I think it's more of a new feature than an enhancement.
It requires a new (composite) node with quite different internals and GUI.
It is definitely a good convenience, but regarding limited time and resources, I would not plan for it.
Of course a pull-request is very welcome.
