### ISSUE TITLE
Enhancement: Dialog with Monolog option

### ISSUE THREAD

**Issue by MJacred** [mhgolkar/Arrow#49]
When a NPC asks the player sth. or gives them the chance to respond to a statement, they usually say something beforehand.  
Adding Monolog into Dialog would reduce the need for another node.

Mockup:

![image](https://user-images.githubusercontent.com/6639237/235373072-e2edfc41-6a7a-4d8e-afa0-552566d94f34.png)

**Comment by mhgolkar** [comment]
The conversation system in Arrow is partial and atomic.

It means we have some general rules/features including but not limited to:
+ Only one owner character for each part of the conversation is needed or can exist.
   > In your case is the character owning the monolog, the dialog or both?
+ All characters can be playable even though they are known to be NPC.

This is a little unorthodox but allows a very flexible system.
I prefer to follow this approach but depending on your needs, you can have a custom node breaking the rules.

God bless open-source.

You may also check out our [previous discussion](https://github.com/mhgolkar/Arrow/issues/9) on this.
