### ISSUE TITLE
Not clear where arrow stores files

### ISSUE THREAD

**Issue by idbrii** [mhgolkar/Arrow#5]
I'm on Windows, so possibly this is more of a problem there where users aren't intended to look in AppData.

When you save you get this dialog that doesn't hint at the storage location: 
![image](https://user-images.githubusercontent.com/43559/110535159-c5823900-80d4-11eb-894a-1bcead6697ab.png)

The quickstart says:

> Arrow keeps all the projects in a single work directory.

> This directory is by default user:// or the platform-specific directory for the user local data.

> You can change work directory from Preferences panel.

But when I click Browse to change that location, it opens the Arrow.exe directory instead of where it's actually put the files.

So since I didn't change the location on first use, my projects are lost (to a nontechnical user). (The path is actually `%userprofile%\AppData\Roaming\Godot\app_userdata\Arrow`)

I'd suggest:

*  show the output directory (readonly) when saving. 
*  Browse in preferences should start at the current project folder 
* add a "open projects location" button somewhere (preferences?)

**Comment by mhgolkar** [comment]
It's done in v1.0.1.
Thanks a lot for the feedback.
