### ISSUE TITLE
Enhancement: Allow Frames to be put behind other nodes

### ISSUE THREAD

**Issue by frigvid** [mhgolkar/Arrow#51]
Currently Frames serve the purpose of letting end-users organize nodes into categories in the same Scene. However, it suffers in terms of UX, as the user has to unnecessarily collapse the frame to access nodes behind it, instead of the frame being able to be placed behind the nodes instead. This is pretty common behavior in other node-based systems, and I think it'd be a valuable enhancement to have such a feature implemented. Frame Labels won't need much special consideration, as this only comes down to the Frame's placement on the canvas, and can be left up to the end-user.

Optionally, and something I'd prefer and appreciate to see, is to also have a toggle that lets Frames have color filled even when not selected. The wireframe is okay, but a color fill is pretty usual for node-based systems that implement groups (like Frames). See the picture below, if you need further clarification.

![image](https://github.com/mhgolkar/Arrow/assets/67565373/377cf606-b984-4757-bc32-98a29f526733)
_Image source: https://medium.com/@umarkhandev/node-based-coding-7433424fa4b0_

***e:*** I've rewritten the issue to better fit the issue, considering I didn't know the purpose of Frames at the time of making the issue.

**Comment by mhgolkar** [comment]
Hi @frigvid 

Yes, our built-in Frame nodes needed some attention.
Recent commit [`a18e90f`] adds a new behavior to keep Frames under their wrapped nodes,
and since they tend to stay there, I think a fill can now be a reasonable default as well.

Thanks for the feedback.

[`a18e90f`]: https://github.com/mhgolkar/Arrow/commit/a18e90f7681202a30af05ecb36f416a4e2d35503

**Comment by mhgolkar** [comment]
I try to keep the main branch stable enough somewhere around beta or if possible release candidate level.

To use the latest version you can of course [build from source].

But there is another way I sometimes suggest, which is using the source directly!

Arrow is developed using Godot game engine which has an interesting feature:
If you copy the right version of Godot Engine executable (one single file) in the root of a game project (here Arrow) and run it, the game will be run as if exported with debug mode.
So if you want the absolutely cutting edge! or you want to change any part of Arrow, this can make it straightforward:
1. Clone Arrow from this git repository
2. Download [Godot Engine] executable (at the time of this comment [v3.5.x-stable])
3. Copy the executable into the root of the cloned Arrow project (where `project.godot` file is)
4. Optionally rename the Godot executable (to `Arrow`, `Arrow.exe`, etc. depending on your OS)
5. Run the executable and enjoy
6. You can `.ignore` the executable and other artifacts created on the fly, so you can easily pull new commits

Hope you find it helpful

[v3.5.x-stable]: https://godotengine.org/download/archive/3.5.3-stable
 [Godot Engine]: https://godotengine.org/download/archive/
 [build from source]: https://github.com/mhgolkar/Arrow/wiki/build-from-source

**Comment by frigvid** [comment]
Neat, I'll go ahead and try this. I've only messed around with Godot shortly before, but I'm sure I'll manage. :)
