### ISSUE TITLE
Feature: Node that plays audio

### ISSUE THREAD

**Issue by frigvid** [mhgolkar/Arrow#53]
As mentioned in #52, I understand that this may be out of scope due to text-based games predominantly being just text. But like with images, I think it'd be nice to have the ability to play some arbitrary audio, be that some small notification sound, or some background music or the like. Not sure how you'd deal with playing music over the course of multiple nodes, without either compromising like simply letting it play until it ends, and/or fading it out when new audio is played. Regardless of the actual implementation, I'd certainly appreciate it.

**Comment by mhgolkar** [comment]
Hi again @frigvid 

Runtime -specific features are generally not planned for Arrow, being more of a narrative design helper tool.
Please take a look at the mentioned issue  #52 for a more detailed explanation.

Have a nice time
