### ISSUE TITLE
Feature: Scene-specific variables

### ISSUE THREAD

**Issue by frigvid** [mhgolkar/Arrow#54]
This is mostly for organization purposes. Currently, as far as I understand it, variables seem to be global. And to make something like a text-based game, some will certainly need to be, but some don't need to be. Given how variables are visible to the end-user, they'll either need to prepend some sort of namespace to filter by or live with having a rather cluttered list of variables. Thus, I feel it'd be a very welcome feature to toggle a variable to "private" (or something to that effect), such that it is only available to a specific Scene at a time.

**Comment by mhgolkar** [comment]
Mainly to keep runtime implementation for it as easy as possible, in Arrow, most resources belong to the global space.
In other words all the resources are considered public. 

As for organization purposes, I thought a way to re-list or filter resources for the currently open scene would be a very useful convenience. Recent commit [`c7d98bf`] adds this.

I hope it helps.

Thanks for your valuable feedback.

[`c7d98bf`]: https://github.com/mhgolkar/Arrow/commit/c7d98bfd9849dcd988923ff6714db2f5a620da81
