### ISSUE TITLE
Feature: Array variable type

### ISSUE THREAD

**Issue by frigvid** [mhgolkar/Arrow#55]
Given that you've mentioned in #52 that you try to avoid adding gameplay- or runtime-specific functionality, I suspect this may be the same. However, I'd still like to ask if array variables could be added. It's mostly for more complex logic chains, because it'd significantly reduce the amount of nodes and variables I'd need to use, but I understand if you don't want to add such a thing.

Also, thank you for the help in the other issues.

***e:*** Though, given that the description mentions that Arrow is also for "interactive nonlinear storytelling," I hope it's within scope enough, because that's what I'm testing around for. :)

**Comment by mhgolkar** [comment]
Yes here too, that is part of the rational behind not adding Arrays, besides keeping the *runtime implementation \[too] easy*. But I also have *never found them needed enough* (in the narrative design context) to go into the hassle of implementing them and accept what comes after. You should consider that it is not about just adding array variables. It is also about all the new nodes, UI, and functionalities to be implemented as well, so they are going to be really working and useful.
Many times, you can handle things (even easier) by overusing (e.g. *str as array-like*) variables, or when some kind of encapsulation is needed [Character tags] for arbitrary entities as characters. For example `_hero_inventory` being a character itself and tags representing the items. I see character tags more as nice general-purpose dictionaries/maps.
Array (-variable) may be a welcome feature (specially if someone comes forward with a perfect PR); but until a real universal need is justifying it, I think we should focus on much more needed and long-awaited matters.

[Character tags]: https://github.com/mhgolkar/Arrow/wiki/characters#tags

**Comment by frigvid** [comment]
That's fair, I expected as much. Amusingly enough, I've also gone the route of having a Character act as storage in my test setup. Literally just a regular storage chest. Though I've not been able to think of a good way to present the user with the contents of the "inventory," so to speak. At least not in a less or not cumbersome way. Any ideas? You don't need to answer, of course, it's just if you have time.

**Comment by mhgolkar** [comment]
Character tags can be injected/printed in the main content nodes using the `{Character.tag_name}` placeholders, similar to the `{variable}` placeholders. Aside from that, other ways to represent them, go into the game-play/runtime -specific category. For example, our official HTML-JS runtime provides [some basic helpers] exposing them as attributes.
Also take a look at [Tag-Edit], [Tag-Match] and [Tag-Pass] nodes to update, check and branch on your inventory items.

[some basic helpers]: https://github.com/mhgolkar/Arrow/tree/main/runtimes/html-js#css-styling-helpers
[Tag-Edit]: https://github.com/mhgolkar/Arrow/wiki/tag-edit
[Tag-Match]: https://github.com/mhgolkar/Arrow/wiki/tag-match
[Tag-Pass]: https://github.com/mhgolkar/Arrow/wiki/tag-pass
