### ISSUE TITLE
Add better item sorting mechanisms to nodes with multiple choices such as Interaction & Dialog

### ISSUE THREAD

**Issue by frigvid** [mhgolkar/Arrow#56]
Currently, the only way to sort Actions in an Interaction node, is to right-click them to edit, set that, and then do it for everything else when you want them in a certain order. This is quite cumbersome and pretty bad from a UX standpoint, and could be improved with drag-and-drop functionality for placement and instead removing the edit-and-set causing the Action to be set to the end of the list. New actions obviously should, however.

**Comment by mhgolkar** [comment]
You also have *alphabetical sort*, *move to top*, and you can *double-click to pick* on an item (instead of right-click to extract), then choose *replace selected ...* to edit it while keeping the order.

But yes, list sorting is quite basic, overall.

I guess we need to at least add *move up* and *move down* functions (maybe with PgUp/Dn shortcuts).
Drag and drop would be nice, but I should check how good it's going to work. Godot does not offer such things by default so we should make them ourselves.

I'd put it in my to-do list. This would be a UX priority.

**Comment by frigvid** [comment]
I haven't looked at how you're storing Actions in the Interaction list, but if it's a list or array, you can just resort them based on the order the user places them in. Still a bit of a hack, but I think it'd work fine. If you're going the keyboard shortcut route, I'd recommend using a modifier key plus an arrow key instead of the Page Up or Page Down keys, as not every keyboard has those easily available. My personal keyboard doesn't have them at all, for example, and I've seen some laptops drop them too. It isn't usual, but I wouldn't call it particularly rare either, so something to keep in mind.

**Comment by mhgolkar** [comment]
> I haven't looked at how you're storing Actions in the Interaction list, but if it's a list or array, you can just resort them based on the order the user places them in.

Newly added choices are always appended at the end of the underlying list/array.
No sorting happens automatically, because the order of choices (i.e. order of slots) would change branching, which shall always be avoided unless the author deliberately decides to do so.

**Comment by frigvid** [comment]
Of course, but in the event that sorting is necessary or desired, I think it's safe to assume that the end-user is inspecting the node because it isn't an automatic feature and thus keeping track of such things on their own. Adding Actions do still mess up branching when you manually sort anyhow, so it doesn't really make much of a difference, it just makes it less cumbersome to do so.

**Comment by mhgolkar** [comment]
We only keep the choices (pieces of text) themselves, so few sorting functions comes to the mind.
Aside from current ones (such as alphabetical sort, and move to the top), and moving them up and down manually which we've agreed upon, do you have any other sorting mechanism in mind?

**Comment by frigvid** [comment]
Hmm, no, I do think that's enough to cover most bases if we're being optimistic. There are probably ways to make it better, but I can't think of any myself, at least. Drag-and-drop, if implemented, should cover all use-cases though, if only because it makes sorting quicker.

**Comment by mhgolkar** [comment]
Lists now offer more sorting mechanisms and new [shortcuts](https://github.com/mhgolkar/Arrow/wiki/shortcuts#item-lists).
Thanks for your suggestion
