### ISSUE TITLE
Let floating panels (Inspector & Console) keep their user-defined size and position between runs

### ISSUE THREAD

**Issue by frigvid** [mhgolkar/Arrow#57]
I tend to resize the Inspector window, so that I see all the tabs at once, instead of having to page through them. However, currently, it resets to its default size after having restarted the application. I think it'd be quite nice to be able to have it remember its size, or at least let users set a new personalized default after resizing it.

(Also, sorry for all the new issue prompts. Hope it isn't too much of a bother.)

**Comment by mhgolkar** [comment]
Yes a convenience for sure, less priority though.
I think it should apply to the other panel(s) like console as well.

**Comment by mhgolkar** [comment]
Recent commits add this.
It is quite rough though, and depending on the OS (and/or window manager) glitches are expected.
Tracked information is kept in the `config.arrow` file. In case of unexpected behavior, removing that file may help.
