### ISSUE TITLE
Bug: Selecting and unselecting a frame causes a change to the scene

### ISSUE THREAD

**Issue by frigvid** [mhgolkar/Arrow#58]
Related to #51 and on the latest commit in the debug version. When selecting a frame, and unselecting it by clicking the canvas somewhere empty, it causes a change that lets you save. I presume this shouldn't be the case, as I cannot remember this having been an issue on the latest release. It's not a large issue, of course, and it's not like I can't save. But I thought I ought to mention it.

**Comment by mhgolkar** [comment]
No, it is not really a bug! It is software OCD!
Arrow's history and saving system is quite aggressive. If you *update an internal state*, it is considered a change in the document and save state flag goes active, even if it is not a real *change in the content or project*.
Now add the  **Auto Inspect** (on selection)  and **Auto Update Node**  (on release) systems, which are quick preferences and both active by default, to the formula. That combination of systems automatically marks any inspected (i.e. selected and released) node as updated, so a potential change to be saved. If you deactivate the *Auto Update Node*, things behave normal but you should remember to manually update inspected resources if you change anything.
It may change in the future, maybe by adding some kind of diff in the process; but for now, let's accept it!
