### ISSUE TITLE
Read only dialogue nodes

### ISSUE THREAD

**Issue by andersmmg** [mhgolkar/Arrow#6]
There's not really a good way (as far as I can tell) to create a dialogue where a character just says something and you continue. Currently, I've just been either creating a dialogue node with only one option as the content which means you have to click it, or just using a content node, but that doesn't have an option to mark a character. An option to add characters to content nodes or a way to use dialogue nodes without any options and some content instead.

**Comment by mhgolkar** [comment]
Have you tried **toggling the `Playable` checkbox off** ?

When you make a Dialog node none-playable, the Arrow console and runtime(s) will auto-play that.
If there is only one line of dialog, it'll be printed and you continue to the next node.
When there are more than one lines of dialog, one of them will be played *randomly* and you continue to the next node.

The `playable` checkbox is right under the list of dialog lines in the `Node` tab of the `Inspector` panel and is on by default.
