### ISSUE TITLE
move only User Input node crash Arrow

### ISSUE THREAD

**Issue by Snakemonster** [mhgolkar/Arrow#61]
Hi there, found a strange bug.
To reproduce it: Open 'Hello World' project -> RMB on empty place -> place node User Input -> try to move this node somewhere by mouse -> crash.

**Comment by YMU-Linux** [comment]
this on linux debian 12 as well as on the web version please fix it is on click web freezes app crashes.

**Comment by mhgolkar** [comment]
Hi
This should be fixed now.
Thanks for the feedback.
