### ISSUE TITLE
Undo and Redo doesn't work on graph  {Linux Pop!_OS}

### ISSUE THREAD

**Issue by AirckLima** [mhgolkar/Arrow#62]
I using Arrow for the first time, and when i try to undo a change **nothing happens even clicking on undo/redo buttons**.

I tested **2.2 x86**, **2.2 x86_64** and  versions and both has the same problem.

The ```history > size```  option __doesnt change__ (always **0**) as well.

---

https://github.com/mhgolkar/Arrow/assets/93441113/835871f6-6b87-4e92-ba30-cdd2ed1f6b6f

---
## OBS: undo and redo work properly on inspector

**Comment by mhgolkar** [comment]
Hi @AirckLima 

It should be fixed now.
Thanks for the feedback.

In general the undo/redo functionality is still experimental and unpolished.
It is literally tracking and rotating multiple snapshots/copies of your project in memory.
I highly recommend having VCS and backup(s) by your side!

Have a nice adventure
