### ISSUE TITLE
Font problems on Debian 12 

### ISSUE THREAD

**Issue by toinebeg** [mhgolkar/Arrow#64]
Hi thanks for this great tool. 

I'm seeing a problem on Debian 12 using gnome 43.9 and wayland, all font are rendered as squares. 

![Screenshot from 2024-05-27 10-06-55](https://github.com/mhgolkar/Arrow/assets/3091094/15cd9fdd-1400-4323-87c8-836ada8bdf9c)

Tell me if you need further testing, I'm available to help. In the meantime I'll keep exploring the web version. 

Thanks.

**Comment by mhgolkar** [comment]
I close this issue for now. Feel free to reply or open a new one if the problem needs to be reconsidered.
